[package]
name = "dynamo_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.1.1"
aws-sdk-dynamodb = "1.9.0"
crossterm = "0.27.0"
ratatui = "0.25.0"
tokio = {version = "1.35.1", features = ["full"]}
